#JBOSS Instalation Code

- name: Install Java 1.7 and some basic dependencies
  yum: 
    name: "{{ item }}"
    state: present
  with_items:
   - unzip
   - java-1.7.0-openjdk
   
- name: Download JBoss from jboss.org
  get_url: 
    url: http://download.jboss.org/jbossas/7.1/jboss-as-7.1.1.Final/jboss-as-7.1.1.Final.zip 
    dest: /opt/jboss-as-7.1.1.Final.zip
    
    
- name: Extract archive
  unarchive: 
    dest: /usr/share 
    src: /opt/jboss-as-7.1.1.Final.zip 
    copy: no

- name: Rename install directory
  command: /bin/mv /usr/share/jboss-as-7.1.1.Final /usr/share/jboss-as
  
- name: Copying standalone.xml configuration file
  copy: 
    src: standalone.xml 
    dest: /usr/share/jboss-as/standalone/configuration/
  notify: restart jboss
  
- name: Copying standalone.sh
  copy: 
    src: jboss-as-standalone.sh 
    dest: /etc/init.d/jboss 
    
- name: Add group "jboss"
  group: 
    name: jboss

- name: Add user "jboss"
  user: 
    name: jboss 
    group: jboss 
    home: /usr/share/jboss-as
