#install the ec2 instance

- name: Provision instances
  hosts: localhost
  connection: local
  gather_facts: False
  ignore_errors: True

  # load AWS variables from this group vars file
  vars_files:
  - group_vars/all

  tasks:

  - file: path=/etc/ansible/logs/ansiblelog.json   state=absent
  - file: path=/etc/ansible/logs/ansiblelog.json   state=touch


  - name: Launch instances
    ec2:
      access_key: "{{ ec2_access_key }}"
      secret_key: "{{ ec2_secret_key }}"
      keypair: "{{ ec2_keypair }}"
      group: "{{ ec2_security_group }}"
      type: "{{ ec2_instance_type }}"
      image: "{{ ec2_image }}"
      region: "{{ ec2_region }}"
      instance_tags: "{'ansible_group':'jboss', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'{{ machine_name }}'}"
      count: "{{ ec2_instance_count }}"
      wait: true
    register: ec2


  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22 
      delay: 60 
      timeout: 320 
      state: started
    with_items: "{{ ec2.instances }}"
  
  - name: Debug info
    debug: var=ec2

  - copy:
         content: "{{ec2}}"
         dest: "/etc/ansible/logs/ansiblelog.json"  

  - copy:
        content: "{{ item.public_dns_name }}"
        dest: "/etc/ansible/hosts"
    with_items: "{{ ec2.instances }}" 
